[workspace]
members = [
	"client/cli",
	"client/consensus/aura",
	"client/consensus/common",
	"client/consensus/relay-chain",
	"client/network",
	"client/pov-recovery",
	"client/service",
	"pallets/aura-ext",
	"pallets/collator-selection",
	"pallets/dmp-queue",
	"pallets/parachain-system",
	"pallets/parachain-system/proc-macro",
	"pallets/session-benchmarking",
	"pallets/xcm",
	"pallets/xcmp-queue",
	"primitives/core",
	"primitives/parachain-inherent",
	"primitives/timestamp",
	"primitives/utility",
	"polkadot-parachains/",
	"polkadot-parachains/pallets/parachain-info",
	"polkadot-parachains/pallets/ping",
	"polkadot-parachains/rococo-runtime",
	"polkadot-parachains/shell-runtime",
	"polkadot-parachains/statemint-common",
	"polkadot-parachains/statemint-runtime",
	"polkadot-parachains/statemine-runtime",
	"polkadot-parachains/westmint-runtime",
	"test/runtime",
	"test/runtime-upgrade",
	"test/client",
	"test/service",
	"test/relay-sproof-builder",
	"test/relay-validation-worker-provider",
]

[profile.release]
panic = "unwind"
[patch."https://github.com/paritytech/polkadot"]
polkadot-cli ={path = "/home/lilpep/dev/polkadot-2/cli" }
polkadot-node-core-pvf ={path = "/home/lilpep/dev/polkadot-2/node/core/pvf" }
polkadot-core-primitives ={path = "/home/lilpep/dev/polkadot-2/core-primitives" }
polkadot-parachain ={path = "/home/lilpep/dev/polkadot-2/parachain" }
test-parachain-adder ={path = "/home/lilpep/dev/polkadot-2/parachain/test-parachains/adder" }
test-parachain-halt ={path = "/home/lilpep/dev/polkadot-2/parachain/test-parachains/halt" }
polkadot-service ={path = "/home/lilpep/dev/polkadot-2/node/service" }
kusama-runtime ={path = "/home/lilpep/dev/polkadot-2/runtime/kusama" }
pallet-xcm ={path = "/home/lilpep/dev/polkadot-2/xcm/pallet-xcm" }
xcm ={path = "/home/lilpep/dev/polkadot-2/xcm" }
xcm-executor ={path = "/home/lilpep/dev/polkadot-2/xcm/xcm-executor" }
polkadot-primitives ={path = "/home/lilpep/dev/polkadot-2/primitives" }
polkadot-runtime-common ={path = "/home/lilpep/dev/polkadot-2/runtime/common" }
polkadot-runtime-parachains ={path = "/home/lilpep/dev/polkadot-2/runtime/parachains" }
slot-range-helper ={path = "/home/lilpep/dev/polkadot-2/runtime/common/slot_range_helper" }
xcm-builder ={path = "/home/lilpep/dev/polkadot-2/xcm/xcm-builder" }
polkadot-approval-distribution ={path = "/home/lilpep/dev/polkadot-2/node/network/approval-distribution" }
polkadot-node-network-protocol ={path = "/home/lilpep/dev/polkadot-2/node/network/protocol" }
polkadot-node-jaeger ={path = "/home/lilpep/dev/polkadot-2/node/jaeger" }
polkadot-node-primitives ={path = "/home/lilpep/dev/polkadot-2/node/primitives" }
polkadot-statement-table ={path = "/home/lilpep/dev/polkadot-2/statement-table" }
polkadot-node-subsystem ={path = "/home/lilpep/dev/polkadot-2/node/subsystem" }
polkadot-procmacro-subsystem-dispatch-gen ={path = "/home/lilpep/dev/polkadot-2/node/subsystem/dispatch-gen" }
polkadot-node-subsystem-test-helpers ={path = "/home/lilpep/dev/polkadot-2/node/subsystem-test-helpers" }
polkadot-node-subsystem-util ={path = "/home/lilpep/dev/polkadot-2/node/subsystem-util" }
metered-channel ={path = "/home/lilpep/dev/polkadot-2/node/metered-channel" }
polkadot-overseer ={path = "/home/lilpep/dev/polkadot-2/node/overseer" }
polkadot-procmacro-overseer-subsystems-gen ={path = "/home/lilpep/dev/polkadot-2/node/overseer/subsystems-gen" }
polkadot-availability-bitfield-distribution ={path = "/home/lilpep/dev/polkadot-2/node/network/bitfield-distribution" }
polkadot-availability-distribution ={path = "/home/lilpep/dev/polkadot-2/node/network/availability-distribution" }
polkadot-erasure-coding ={path = "/home/lilpep/dev/polkadot-2/erasure-coding" }
polkadot-node-core-runtime-api ={path = "/home/lilpep/dev/polkadot-2/node/core/runtime-api" }
polkadot-availability-recovery ={path = "/home/lilpep/dev/polkadot-2/node/network/availability-recovery" }
polkadot-client ={path = "/home/lilpep/dev/polkadot-2/node/client" }
polkadot-runtime ={path = "/home/lilpep/dev/polkadot-2/runtime/polkadot" }
rococo-runtime ={path = "/home/lilpep/dev/polkadot-2/runtime/rococo" }
bp-rococo ={path = "/home/lilpep/dev/polkadot-2/bridges/primitives/chain-rococo" }
bp-header-chain ={path = "/home/lilpep/dev/polkadot-2/bridges/primitives/header-chain" }
bp-test-utils ={path = "/home/lilpep/dev/polkadot-2/bridges/primitives/test-utils" }
bp-messages ={path = "/home/lilpep/dev/polkadot-2/bridges/primitives/messages" }
bp-runtime ={path = "/home/lilpep/dev/polkadot-2/bridges/primitives/runtime" }
bp-polkadot-core ={path = "/home/lilpep/dev/polkadot-2/bridges/primitives/polkadot-core" }
bp-wococo ={path = "/home/lilpep/dev/polkadot-2/bridges/primitives/chain-wococo" }
pallet-bridge-grandpa ={path = "/home/lilpep/dev/polkadot-2/bridges/modules/grandpa" }
westend-runtime ={path = "/home/lilpep/dev/polkadot-2/runtime/westend" }
polkadot-collator-protocol ={path = "/home/lilpep/dev/polkadot-2/node/network/collator-protocol" }
polkadot-gossip-support ={path = "/home/lilpep/dev/polkadot-2/node/network/gossip-support" }
polkadot-network-bridge ={path = "/home/lilpep/dev/polkadot-2/node/network/bridge" }
polkadot-node-collation-generation ={path = "/home/lilpep/dev/polkadot-2/node/collation-generation" }
polkadot-node-core-approval-voting ={path = "/home/lilpep/dev/polkadot-2/node/core/approval-voting" }
polkadot-node-core-av-store ={path = "/home/lilpep/dev/polkadot-2/node/core/av-store" }
polkadot-node-core-backing ={path = "/home/lilpep/dev/polkadot-2/node/core/backing" }
polkadot-node-core-bitfield-signing ={path = "/home/lilpep/dev/polkadot-2/node/core/bitfield-signing" }
polkadot-node-core-candidate-validation ={path = "/home/lilpep/dev/polkadot-2/node/core/candidate-validation" }
polkadot-node-core-chain-api ={path = "/home/lilpep/dev/polkadot-2/node/core/chain-api" }
polkadot-node-core-parachains-inherent ={path = "/home/lilpep/dev/polkadot-2/node/core/parachains-inherent" }
polkadot-node-core-provisioner ={path = "/home/lilpep/dev/polkadot-2/node/core/provisioner" }
polkadot-rpc ={path = "/home/lilpep/dev/polkadot-2/rpc" }
polkadot-statement-distribution ={path = "/home/lilpep/dev/polkadot-2/node/network/statement-distribution" }
polkadot-test-client ={path = "/home/lilpep/dev/polkadot-2/node/test/client" }
polkadot-test-runtime ={path = "/home/lilpep/dev/polkadot-2/runtime/test-runtime" }
polkadot-test-service ={path = "/home/lilpep/dev/polkadot-2/node/test/service" }
polkadot-node-core-dispute-coordinator ={path = "/home/lilpep/dev/polkadot-2/node/core/dispute-coordinator" }
test-parachains ={path = "/home/lilpep/dev/polkadot-2/parachain/test-parachains" }
test-parachain-adder-collator ={path = "/home/lilpep/dev/polkadot-2/parachain/test-parachains/adder/collator" }
polkadot ={path = "/home/lilpep/dev/polkadot-2" }
